-- Semilla de políticas de descuento/recargo/gaf/ucc (fase 1): transcripción 1:1
-- de POLITICAS_AGOSTO del cotizador legacy (medife_cotizador_individual.html).
-- La categoría "ambas" del legacy se representa con categoria_scope = null (sin filtro).

insert into discount_policies (id, nombre, tipo, region, categoria_scope, procedencia_gate, zona_filial, valor_pct, permanente, plazo_meses, concatenable, detalle) values
  ('prestadores-medife-amba', 'PRESTADORES MEDIFE AMBA', 'gaf', 'AMBA', null, 'GAF', null, -0.15, true, null, false, 'Val sobre valor final'),
  ('clientes-tributo-simple', 'CLIENTES TRIBUTO SIMPLE', 'gaf', 'Nac', null, 'GAF', null, -0.1, true, null, false, 'Val sobre valor final'),
  ('planes-empleados-10', 'PLANES EMPLEADOS 10%', 'gaf', 'Nac', 'Obl', 'GAF', null, -0.1, true, null, false, 'Val sobre valor final'),
  ('planes-empleados-15', 'PLANES EMPLEADOS 15%', 'gaf', 'Nac', 'Obl', 'GAF', null, -0.15, true, 12, false, 'Val sobre valor final'),
  ('acipan', 'ACIPAN', 'gaf', 'SurExt', null, 'GAF', null, -0.1, true, 12, false, 'Val sobre valor final'),
  ('camara-bariloche', 'CAMARA DE COMERCIO BARILOCHE', 'gaf', 'SurExt', null, 'GAF', null, -0.1575, true, 12, false, 'Val sobre valor final'),
  ('ex-invap-jubilados', 'EX INVAP JUBILADOS', 'gaf', 'SurExt', null, 'GAF', null, -0.3, true, 12, false, 'Val sobre valor final'),
  ('prestadores-medife-sur', 'PRESTADORES MEDIFE SUR', 'gaf', 'SurExt', null, 'GAF', null, -0.15, true, 12, false, 'Val sobre valor final'),
  ('prestadores-medife-norte', 'PRESTADORES MEDIFE NORTE', 'gaf', 'Norte', null, 'GAF', null, -0.15, true, 12, false, 'Val sobre valor final'),
  ('ucc', 'UCC', 'ucc', 'Norte', null, 'GAF', null, -0.15, true, null, false, 'Empleador acumulable'),
  ('recargo-comahue-Obl', 'Recargo Comahue Obl', 'recargo', 'Sur', 'Obl', '', 'Comahue', 0.16, true, null, false, 'Comahue +16%'),
  ('recargo-patagonia-sur-Obl', 'Recargo Patagonia Sur Obl', 'recargo', 'Sur', 'Obl', '', 'Patagonia Sur', 0.16, true, null, false, 'Patagonia Sur +16%'),
  ('recargo-patagonia-norte-Obl', 'Recargo Patagonia Norte Obl', 'recargo', 'Sur', 'Obl', '', 'Patagonia Norte', 0.16, true, null, false, 'Patagonia Norte +16%'),
  ('recargo-comahue-Vol', 'Recargo Comahue Vol', 'recargo', 'Sur', 'Vol', '', 'Comahue', 0.26, true, null, false, 'Comahue +26%'),
  ('recargo-patagonia-sur-Vol', 'Recargo Patagonia Sur Vol', 'recargo', 'Sur', 'Vol', '', 'Patagonia Sur', 0.26, true, null, false, 'Patagonia Sur +26%'),
  ('recargo-patagonia-norte-Vol', 'Recargo Patagonia Norte Vol', 'recargo', 'Sur', 'Vol', '', 'Patagonia Norte', 0.26, true, null, false, 'Patagonia Norte +26%'),
  ('recargo-bahia-Vol', 'Recargo Bahía/MDQ Vol', 'recargo', 'Sur', 'Vol', '', 'Bahía Blanca,Mar del Plata', 0.05, true, null, false, 'Bahía Blanca / Mar del Plata +5%'),
  ('segmento-joven-h-29-amba-Vol', 'Segmento Joven h/29', 'dto', 'AMBA', 'Vol', '', null, -0.13, true, null, false, 'Titulares_Hasta 29 años y 11 meses'),
  ('segmento-joven-h-29-amba-Obl', 'Segmento Joven h/29', 'dto', 'AMBA', 'Obl', '', null, -0.13, true, null, false, 'Titulares_Hasta 29 años y 11 meses'),
  ('segmento-joven-h-25-amba-Vol', 'Segmento Joven h/25', 'dto', 'AMBA', 'Vol', '', null, -0.26, true, null, false, 'Titulares_Hasta 25 años y 11 meses'),
  ('segmento-joven-h-25-amba-Obl', 'Segmento Joven h/25', 'dto', 'AMBA', 'Obl', '', null, -0.26, true, null, false, 'Titulares_Hasta 25 años y 11 meses'),
  ('segmento-joven-h-25-interior-Vol', 'Segmento Joven h/25', 'dto', 'Interior', 'Vol', '', null, -0.26, true, null, false, 'Titulares y Conyugues_Hasta 25 años y 11 meses'),
  ('segmento-joven-h-25-interior-Obl', 'Segmento Joven h/25', 'dto', 'Interior', 'Obl', '', null, -0.26, true, null, false, 'Titulares y Conyugues_Hasta 25 años y 11 meses'),
  ('ajuste-lista-hijos-amba-Obl', 'Ajuste lista Hijos', 'dto', 'AMBA', 'Obl', '', null, -0.45, true, null, false, 'Ajuste lista Hijos (hasta 25 años en AMBA)'),
  ('ajuste-lista-hijos-amba-Vol', 'Ajuste lista Hijos', 'dto', 'AMBA', 'Vol', '', null, -0.45, true, null, false, 'Ajuste lista Hijos (hasta 25 años en AMBA)'),
  ('ajuste-lista-hijos-interior-Obl', 'Ajuste lista Hijos', 'dto', 'Interior', 'Obl', '', null, -0.55, true, null, false, 'Ajuste lista Hijos'),
  ('ajuste-lista-hijos-interior-Vol', 'Ajuste lista Hijos', 'dto', 'Interior', 'Vol', '', null, -0.55, true, null, false, 'Ajuste lista Hijos'),
  ('descuento-filial-noa-Obl', 'Descuento Filial NOA', 'dto', 'Norte', 'Obl', '', 'NOA', -0.2, true, null, false, 'NOA -20%'),
  ('descuento-filial-misiones-corrientes-Obl', 'Descuento Filial Misiones/Corrientes', 'dto', 'Norte', 'Obl', '', 'Misiones,Corrientes', -0.25, true, null, false, 'Misiones, Corrientes -25%'),
  ('descuento-filial-cordoba-Obl', 'Descuento Filial Córdoba', 'dto', 'Norte', 'Obl', '', 'Córdoba', -0.1, true, null, false, 'Córdoba -10%'),
  ('descuento-filial-santa-fe-Obl', 'Descuento Filial Santa Fe', 'dto', 'Norte', 'Obl', '', 'Santa Fe', -0.05, true, null, false, 'Santa Fe -5%'),
  ('opcion-1-nac-Vol', 'Opción 1', 'dto', 'Nac', 'Vol', '', null, -0.3, false, 7, false, '30% × 3; 20% × 2; 10% × 2'),
  ('opcion-2-nac-Vol', 'Opción 2', 'dto', 'Nac', 'Vol', '', null, -0.3, false, 9, false, '30% × 3; 10% × 6'),
  ('opcion-3-nac-Vol', 'Opción 3', 'dto', 'Nac', 'Vol', '', null, -0.15, false, 10, false, '15% × 10 meses'),
  ('opcion-4-nac-Vol', 'Opción 4', 'dto', 'Nac', 'Vol', 'comprobable', null, -0.15, false, 12, false, '15% × 12 · Con procedencia comprobable'),
  ('opcion-5-nac-Vol', 'Opción 5', 'dto', 'Nac', 'Vol', 'comprobable', null, -0.05, false, 6, true, '5% × 6 · Concatenable con Op 1,2,3'),
  ('opcion-1-nac-Obl', 'Opción 1', 'dto', 'Nac', 'Obl', '', null, -0.45, false, 7, false, '45% × 2; 30% × 3; 15% × 2'),
  ('opcion-2-nac-Obl', 'Opción 2', 'dto', 'Nac', 'Obl', '', null, -0.3, false, 9, false, '30% × 6; 10% × 3'),
  ('opcion-3-nac-Obl', 'Opción 3', 'dto', 'Nac', 'Obl', '', null, -0.2, false, 11, false, '20% × 11 meses'),
  ('opcion-4-nac-Obl', 'Opción 4', 'dto', 'Nac', 'Obl', 'comprobable', null, -0.2, false, 12, true, '20% × 12 · Con procedencia comprobable'),
  ('opcion-5-nac-Obl', 'Opción 5', 'dto', 'Nac', 'Obl', 'comprobable', null, -0.05, false, 6, true, '5% × 6 · Concatenable con Op 1,2,3'),
  ('dto-mes-18-65-amba-oro-Obl', 'Dto Mes ORO 18/65', 'dto', 'AMBA', 'Obl', '', null, -0.1, false, 6, false, 'ORO 18 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-41-65-amba-plat-Obl', 'Dto Mes Platinum 41/65', 'dto', 'AMBA', 'Obl', '', null, -0.1, false, 6, false, 'Platinum 41 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-amba-oro-Vol', 'Dto Mes ORO 36/65', 'dto', 'AMBA', 'Vol', '', null, -0.1, false, 6, false, 'ORO 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-65-sur-oro-Obl', 'Dto Mes ORO 18/65', 'dto', 'Sur', 'Obl', '', null, -0.1, false, 6, false, 'ORO 18 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-indie-18-25-amba-Obl', 'Dto Indie 18/25', 'dto', 'AMBA', 'Obl', '', null, -0.185, false, 12, false, 'Indie 18 a 25 años'),
  ('dto-indie-26-35-amba-Obl', 'Dto Indie 26/35', 'dto', 'AMBA', 'Obl', '', null, -0.2, false, 12, false, 'Indie 26 a 35 años'),
  ('dto-indie-36-40-amba-Obl', 'Dto Indie 36/40', 'dto', 'AMBA', 'Obl', '', null, -0.28, false, 12, false, 'Indie 36 a 40 años');

insert into discount_policy_plan_rules (discount_policy_id, plan_code, aplica) values
  ('prestadores-medife-amba', 'INDIE', true),
  ('prestadores-medife-amba', 'MEDIFEPLUS', true),
  ('prestadores-medife-amba', 'BRONCE_C', true),
  ('prestadores-medife-amba', 'BRONCE', true),
  ('prestadores-medife-amba', 'PLATA', true),
  ('prestadores-medife-amba', 'ORO', true),
  ('prestadores-medife-amba', 'PLATINUM', true),
  ('clientes-tributo-simple', 'INDIE', true),
  ('clientes-tributo-simple', 'MEDIFEPLUS', true),
  ('clientes-tributo-simple', 'BRONCE_C', true),
  ('clientes-tributo-simple', 'BRONCE', true),
  ('clientes-tributo-simple', 'PLATA', true),
  ('clientes-tributo-simple', 'ORO', true),
  ('clientes-tributo-simple', 'PLATINUM', true),
  ('planes-empleados-10', 'INDIE', true),
  ('planes-empleados-10', 'MEDIFEPLUS', true),
  ('planes-empleados-10', 'BRONCE_C', true),
  ('planes-empleados-10', 'BRONCE', true),
  ('planes-empleados-10', 'PLATA', true),
  ('planes-empleados-10', 'ORO', true),
  ('planes-empleados-10', 'PLATINUM', true),
  ('planes-empleados-15', 'INDIE', true),
  ('planes-empleados-15', 'MEDIFEPLUS', true),
  ('planes-empleados-15', 'BRONCE_C', true),
  ('planes-empleados-15', 'BRONCE', true),
  ('planes-empleados-15', 'PLATA', true),
  ('planes-empleados-15', 'ORO', true),
  ('planes-empleados-15', 'PLATINUM', true),
  ('acipan', 'INDIE', true),
  ('acipan', 'MEDIFEPLUS', true),
  ('acipan', 'BRONCE_C', true),
  ('acipan', 'BRONCE', true),
  ('acipan', 'PLATA', true),
  ('acipan', 'ORO', true),
  ('acipan', 'PLATINUM', true),
  ('camara-bariloche', 'INDIE', true),
  ('camara-bariloche', 'MEDIFEPLUS', true),
  ('camara-bariloche', 'BRONCE_C', true),
  ('camara-bariloche', 'BRONCE', true),
  ('camara-bariloche', 'PLATA', true),
  ('camara-bariloche', 'ORO', true),
  ('camara-bariloche', 'PLATINUM', true),
  ('ex-invap-jubilados', 'INDIE', true),
  ('ex-invap-jubilados', 'MEDIFEPLUS', true),
  ('ex-invap-jubilados', 'BRONCE_C', true),
  ('ex-invap-jubilados', 'BRONCE', true),
  ('ex-invap-jubilados', 'PLATA', true),
  ('ex-invap-jubilados', 'ORO', true),
  ('ex-invap-jubilados', 'PLATINUM', true),
  ('prestadores-medife-sur', 'INDIE', true),
  ('prestadores-medife-sur', 'MEDIFEPLUS', true),
  ('prestadores-medife-sur', 'BRONCE_C', true),
  ('prestadores-medife-sur', 'BRONCE', true),
  ('prestadores-medife-sur', 'PLATA', true),
  ('prestadores-medife-sur', 'ORO', true),
  ('prestadores-medife-sur', 'PLATINUM', true),
  ('prestadores-medife-norte', 'INDIE', true),
  ('prestadores-medife-norte', 'MEDIFEPLUS', true),
  ('prestadores-medife-norte', 'BRONCE_C', true),
  ('prestadores-medife-norte', 'BRONCE', true),
  ('prestadores-medife-norte', 'PLATA', true),
  ('prestadores-medife-norte', 'ORO', true),
  ('prestadores-medife-norte', 'PLATINUM', true),
  ('ucc', 'INDIE', true),
  ('ucc', 'MEDIFEPLUS', true),
  ('ucc', 'BRONCE_C', true),
  ('ucc', 'BRONCE', true),
  ('ucc', 'PLATA', true),
  ('ucc', 'ORO', true),
  ('ucc', 'PLATINUM', true),
  ('recargo-comahue-Obl', 'INDIE', true),
  ('recargo-comahue-Obl', 'MEDIFEPLUS', true),
  ('recargo-comahue-Obl', 'BRONCE_C', true),
  ('recargo-comahue-Obl', 'BRONCE', true),
  ('recargo-comahue-Obl', 'PLATA', true),
  ('recargo-comahue-Obl', 'ORO', true),
  ('recargo-comahue-Obl', 'PLATINUM', true),
  ('recargo-patagonia-sur-Obl', 'INDIE', true),
  ('recargo-patagonia-sur-Obl', 'MEDIFEPLUS', true),
  ('recargo-patagonia-sur-Obl', 'BRONCE_C', true),
  ('recargo-patagonia-sur-Obl', 'BRONCE', true),
  ('recargo-patagonia-sur-Obl', 'PLATA', true),
  ('recargo-patagonia-sur-Obl', 'ORO', true),
  ('recargo-patagonia-sur-Obl', 'PLATINUM', true),
  ('recargo-patagonia-norte-Obl', 'INDIE', true),
  ('recargo-patagonia-norte-Obl', 'MEDIFEPLUS', true),
  ('recargo-patagonia-norte-Obl', 'BRONCE_C', true),
  ('recargo-patagonia-norte-Obl', 'BRONCE', true),
  ('recargo-patagonia-norte-Obl', 'PLATA', true),
  ('recargo-patagonia-norte-Obl', 'ORO', true),
  ('recargo-patagonia-norte-Obl', 'PLATINUM', true),
  ('recargo-comahue-Vol', 'INDIE', true),
  ('recargo-comahue-Vol', 'MEDIFEPLUS', true),
  ('recargo-comahue-Vol', 'BRONCE_C', true),
  ('recargo-comahue-Vol', 'BRONCE', true),
  ('recargo-comahue-Vol', 'PLATA', true),
  ('recargo-comahue-Vol', 'ORO', true),
  ('recargo-comahue-Vol', 'PLATINUM', true),
  ('recargo-patagonia-sur-Vol', 'INDIE', true),
  ('recargo-patagonia-sur-Vol', 'MEDIFEPLUS', true),
  ('recargo-patagonia-sur-Vol', 'BRONCE_C', true),
  ('recargo-patagonia-sur-Vol', 'BRONCE', true),
  ('recargo-patagonia-sur-Vol', 'PLATA', true),
  ('recargo-patagonia-sur-Vol', 'ORO', true),
  ('recargo-patagonia-sur-Vol', 'PLATINUM', true),
  ('recargo-patagonia-norte-Vol', 'INDIE', true),
  ('recargo-patagonia-norte-Vol', 'MEDIFEPLUS', true),
  ('recargo-patagonia-norte-Vol', 'BRONCE_C', true),
  ('recargo-patagonia-norte-Vol', 'BRONCE', true),
  ('recargo-patagonia-norte-Vol', 'PLATA', true),
  ('recargo-patagonia-norte-Vol', 'ORO', true),
  ('recargo-patagonia-norte-Vol', 'PLATINUM', true),
  ('recargo-bahia-Vol', 'INDIE', true),
  ('recargo-bahia-Vol', 'MEDIFEPLUS', true),
  ('recargo-bahia-Vol', 'BRONCE_C', true),
  ('recargo-bahia-Vol', 'BRONCE', true),
  ('recargo-bahia-Vol', 'PLATA', true),
  ('recargo-bahia-Vol', 'ORO', true),
  ('recargo-bahia-Vol', 'PLATINUM', true),
  ('segmento-joven-h-29-amba-Vol', 'INDIE', false),
  ('segmento-joven-h-29-amba-Vol', 'MEDIFEPLUS', true),
  ('segmento-joven-h-29-amba-Vol', 'BRONCE_C', true),
  ('segmento-joven-h-29-amba-Vol', 'BRONCE', true),
  ('segmento-joven-h-29-amba-Vol', 'PLATA', true),
  ('segmento-joven-h-29-amba-Vol', 'ORO', true),
  ('segmento-joven-h-29-amba-Vol', 'PLATINUM', true),
  ('segmento-joven-h-29-amba-Obl', 'INDIE', false),
  ('segmento-joven-h-29-amba-Obl', 'MEDIFEPLUS', true),
  ('segmento-joven-h-29-amba-Obl', 'BRONCE_C', true),
  ('segmento-joven-h-29-amba-Obl', 'BRONCE', true),
  ('segmento-joven-h-29-amba-Obl', 'PLATA', true),
  ('segmento-joven-h-29-amba-Obl', 'ORO', true),
  ('segmento-joven-h-29-amba-Obl', 'PLATINUM', true),
  ('segmento-joven-h-25-amba-Vol', 'INDIE', false),
  ('segmento-joven-h-25-amba-Vol', 'MEDIFEPLUS', false),
  ('segmento-joven-h-25-amba-Vol', 'BRONCE_C', true),
  ('segmento-joven-h-25-amba-Vol', 'BRONCE', true),
  ('segmento-joven-h-25-amba-Vol', 'PLATA', true),
  ('segmento-joven-h-25-amba-Vol', 'ORO', true),
  ('segmento-joven-h-25-amba-Vol', 'PLATINUM', true),
  ('segmento-joven-h-25-amba-Obl', 'INDIE', true),
  ('segmento-joven-h-25-amba-Obl', 'MEDIFEPLUS', false),
  ('segmento-joven-h-25-amba-Obl', 'BRONCE_C', true),
  ('segmento-joven-h-25-amba-Obl', 'BRONCE', true),
  ('segmento-joven-h-25-amba-Obl', 'PLATA', true),
  ('segmento-joven-h-25-amba-Obl', 'ORO', true),
  ('segmento-joven-h-25-amba-Obl', 'PLATINUM', true),
  ('segmento-joven-h-25-interior-Vol', 'INDIE', false),
  ('segmento-joven-h-25-interior-Vol', 'MEDIFEPLUS', false),
  ('segmento-joven-h-25-interior-Vol', 'BRONCE_C', true),
  ('segmento-joven-h-25-interior-Vol', 'BRONCE', true),
  ('segmento-joven-h-25-interior-Vol', 'PLATA', true),
  ('segmento-joven-h-25-interior-Vol', 'ORO', true),
  ('segmento-joven-h-25-interior-Vol', 'PLATINUM', true),
  ('segmento-joven-h-25-interior-Obl', 'INDIE', false),
  ('segmento-joven-h-25-interior-Obl', 'MEDIFEPLUS', false),
  ('segmento-joven-h-25-interior-Obl', 'BRONCE_C', true),
  ('segmento-joven-h-25-interior-Obl', 'BRONCE', true),
  ('segmento-joven-h-25-interior-Obl', 'PLATA', true),
  ('segmento-joven-h-25-interior-Obl', 'ORO', true),
  ('segmento-joven-h-25-interior-Obl', 'PLATINUM', true),
  ('ajuste-lista-hijos-amba-Obl', 'INDIE', false),
  ('ajuste-lista-hijos-amba-Obl', 'MEDIFEPLUS', true),
  ('ajuste-lista-hijos-amba-Obl', 'BRONCE_C', true),
  ('ajuste-lista-hijos-amba-Obl', 'BRONCE', true),
  ('ajuste-lista-hijos-amba-Obl', 'PLATA', true),
  ('ajuste-lista-hijos-amba-Obl', 'ORO', true),
  ('ajuste-lista-hijos-amba-Obl', 'PLATINUM', true),
  ('ajuste-lista-hijos-amba-Vol', 'INDIE', false),
  ('ajuste-lista-hijos-amba-Vol', 'MEDIFEPLUS', true),
  ('ajuste-lista-hijos-amba-Vol', 'BRONCE_C', true),
  ('ajuste-lista-hijos-amba-Vol', 'BRONCE', true),
  ('ajuste-lista-hijos-amba-Vol', 'PLATA', true),
  ('ajuste-lista-hijos-amba-Vol', 'ORO', true),
  ('ajuste-lista-hijos-amba-Vol', 'PLATINUM', true),
  ('ajuste-lista-hijos-interior-Obl', 'INDIE', false),
  ('ajuste-lista-hijos-interior-Obl', 'MEDIFEPLUS', true),
  ('ajuste-lista-hijos-interior-Obl', 'BRONCE_C', true),
  ('ajuste-lista-hijos-interior-Obl', 'BRONCE', true),
  ('ajuste-lista-hijos-interior-Obl', 'PLATA', true),
  ('ajuste-lista-hijos-interior-Obl', 'ORO', true),
  ('ajuste-lista-hijos-interior-Obl', 'PLATINUM', true),
  ('ajuste-lista-hijos-interior-Vol', 'INDIE', false),
  ('ajuste-lista-hijos-interior-Vol', 'MEDIFEPLUS', true),
  ('ajuste-lista-hijos-interior-Vol', 'BRONCE_C', true),
  ('ajuste-lista-hijos-interior-Vol', 'BRONCE', true),
  ('ajuste-lista-hijos-interior-Vol', 'PLATA', true),
  ('ajuste-lista-hijos-interior-Vol', 'ORO', true),
  ('ajuste-lista-hijos-interior-Vol', 'PLATINUM', true),
  ('descuento-filial-noa-Obl', 'INDIE', false),
  ('descuento-filial-noa-Obl', 'MEDIFEPLUS', true),
  ('descuento-filial-noa-Obl', 'BRONCE_C', true),
  ('descuento-filial-noa-Obl', 'BRONCE', true),
  ('descuento-filial-noa-Obl', 'PLATA', true),
  ('descuento-filial-noa-Obl', 'ORO', true),
  ('descuento-filial-noa-Obl', 'PLATINUM', true),
  ('descuento-filial-misiones-corrientes-Obl', 'INDIE', false),
  ('descuento-filial-misiones-corrientes-Obl', 'MEDIFEPLUS', true),
  ('descuento-filial-misiones-corrientes-Obl', 'BRONCE_C', true),
  ('descuento-filial-misiones-corrientes-Obl', 'BRONCE', true),
  ('descuento-filial-misiones-corrientes-Obl', 'PLATA', true),
  ('descuento-filial-misiones-corrientes-Obl', 'ORO', true),
  ('descuento-filial-misiones-corrientes-Obl', 'PLATINUM', true),
  ('descuento-filial-cordoba-Obl', 'INDIE', false),
  ('descuento-filial-cordoba-Obl', 'MEDIFEPLUS', true),
  ('descuento-filial-cordoba-Obl', 'BRONCE_C', true),
  ('descuento-filial-cordoba-Obl', 'BRONCE', true),
  ('descuento-filial-cordoba-Obl', 'PLATA', true),
  ('descuento-filial-cordoba-Obl', 'ORO', true),
  ('descuento-filial-cordoba-Obl', 'PLATINUM', true),
  ('descuento-filial-santa-fe-Obl', 'INDIE', false),
  ('descuento-filial-santa-fe-Obl', 'MEDIFEPLUS', true),
  ('descuento-filial-santa-fe-Obl', 'BRONCE_C', true),
  ('descuento-filial-santa-fe-Obl', 'BRONCE', true),
  ('descuento-filial-santa-fe-Obl', 'PLATA', true),
  ('descuento-filial-santa-fe-Obl', 'ORO', true),
  ('descuento-filial-santa-fe-Obl', 'PLATINUM', true),
  ('opcion-1-nac-Vol', 'INDIE', false),
  ('opcion-1-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-1-nac-Vol', 'BRONCE_C', true),
  ('opcion-1-nac-Vol', 'BRONCE', true),
  ('opcion-1-nac-Vol', 'PLATA', true),
  ('opcion-1-nac-Vol', 'ORO', true),
  ('opcion-1-nac-Vol', 'PLATINUM', true),
  ('opcion-2-nac-Vol', 'INDIE', false),
  ('opcion-2-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-2-nac-Vol', 'BRONCE_C', true),
  ('opcion-2-nac-Vol', 'BRONCE', true),
  ('opcion-2-nac-Vol', 'PLATA', true),
  ('opcion-2-nac-Vol', 'ORO', true),
  ('opcion-2-nac-Vol', 'PLATINUM', true),
  ('opcion-3-nac-Vol', 'INDIE', false),
  ('opcion-3-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-3-nac-Vol', 'BRONCE_C', true),
  ('opcion-3-nac-Vol', 'BRONCE', true),
  ('opcion-3-nac-Vol', 'PLATA', true),
  ('opcion-3-nac-Vol', 'ORO', true),
  ('opcion-3-nac-Vol', 'PLATINUM', true),
  ('opcion-4-nac-Vol', 'INDIE', false),
  ('opcion-4-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-4-nac-Vol', 'BRONCE_C', true),
  ('opcion-4-nac-Vol', 'BRONCE', true),
  ('opcion-4-nac-Vol', 'PLATA', true),
  ('opcion-4-nac-Vol', 'ORO', true),
  ('opcion-4-nac-Vol', 'PLATINUM', true),
  ('opcion-5-nac-Vol', 'INDIE', false),
  ('opcion-5-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-5-nac-Vol', 'BRONCE_C', true),
  ('opcion-5-nac-Vol', 'BRONCE', true),
  ('opcion-5-nac-Vol', 'PLATA', true),
  ('opcion-5-nac-Vol', 'ORO', true),
  ('opcion-5-nac-Vol', 'PLATINUM', true),
  ('opcion-1-nac-Obl', 'INDIE', false),
  ('opcion-1-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-1-nac-Obl', 'BRONCE_C', true),
  ('opcion-1-nac-Obl', 'BRONCE', true),
  ('opcion-1-nac-Obl', 'PLATA', true),
  ('opcion-1-nac-Obl', 'ORO', true),
  ('opcion-1-nac-Obl', 'PLATINUM', true),
  ('opcion-2-nac-Obl', 'INDIE', false),
  ('opcion-2-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-2-nac-Obl', 'BRONCE_C', true),
  ('opcion-2-nac-Obl', 'BRONCE', true),
  ('opcion-2-nac-Obl', 'PLATA', true),
  ('opcion-2-nac-Obl', 'ORO', true),
  ('opcion-2-nac-Obl', 'PLATINUM', true),
  ('opcion-3-nac-Obl', 'INDIE', false),
  ('opcion-3-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-3-nac-Obl', 'BRONCE_C', true),
  ('opcion-3-nac-Obl', 'BRONCE', true),
  ('opcion-3-nac-Obl', 'PLATA', true),
  ('opcion-3-nac-Obl', 'ORO', true),
  ('opcion-3-nac-Obl', 'PLATINUM', true),
  ('opcion-4-nac-Obl', 'INDIE', false),
  ('opcion-4-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-4-nac-Obl', 'BRONCE_C', true),
  ('opcion-4-nac-Obl', 'BRONCE', true),
  ('opcion-4-nac-Obl', 'PLATA', true),
  ('opcion-4-nac-Obl', 'ORO', true),
  ('opcion-4-nac-Obl', 'PLATINUM', true),
  ('opcion-5-nac-Obl', 'INDIE', false),
  ('opcion-5-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-5-nac-Obl', 'BRONCE_C', true),
  ('opcion-5-nac-Obl', 'BRONCE', true),
  ('opcion-5-nac-Obl', 'PLATA', true),
  ('opcion-5-nac-Obl', 'ORO', true),
  ('opcion-5-nac-Obl', 'PLATINUM', true),
  ('dto-mes-18-65-amba-oro-Obl', 'INDIE', false),
  ('dto-mes-18-65-amba-oro-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-65-amba-oro-Obl', 'BRONCE_C', false),
  ('dto-mes-18-65-amba-oro-Obl', 'BRONCE', false),
  ('dto-mes-18-65-amba-oro-Obl', 'PLATA', false),
  ('dto-mes-18-65-amba-oro-Obl', 'ORO', true),
  ('dto-mes-18-65-amba-oro-Obl', 'PLATINUM', false),
  ('dto-mes-41-65-amba-plat-Obl', 'INDIE', false),
  ('dto-mes-41-65-amba-plat-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-41-65-amba-plat-Obl', 'BRONCE_C', false),
  ('dto-mes-41-65-amba-plat-Obl', 'BRONCE', false),
  ('dto-mes-41-65-amba-plat-Obl', 'PLATA', false),
  ('dto-mes-41-65-amba-plat-Obl', 'ORO', false),
  ('dto-mes-41-65-amba-plat-Obl', 'PLATINUM', true),
  ('dto-mes-36-65-amba-oro-Vol', 'INDIE', false),
  ('dto-mes-36-65-amba-oro-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-amba-oro-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-amba-oro-Vol', 'BRONCE', false),
  ('dto-mes-36-65-amba-oro-Vol', 'PLATA', false),
  ('dto-mes-36-65-amba-oro-Vol', 'ORO', true),
  ('dto-mes-36-65-amba-oro-Vol', 'PLATINUM', false),
  ('dto-mes-18-65-sur-oro-Obl', 'INDIE', false),
  ('dto-mes-18-65-sur-oro-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-65-sur-oro-Obl', 'BRONCE_C', false),
  ('dto-mes-18-65-sur-oro-Obl', 'BRONCE', false),
  ('dto-mes-18-65-sur-oro-Obl', 'PLATA', false),
  ('dto-mes-18-65-sur-oro-Obl', 'ORO', true),
  ('dto-mes-18-65-sur-oro-Obl', 'PLATINUM', false),
  ('dto-indie-18-25-amba-Obl', 'INDIE', true),
  ('dto-indie-18-25-amba-Obl', 'MEDIFEPLUS', false),
  ('dto-indie-18-25-amba-Obl', 'BRONCE_C', false),
  ('dto-indie-18-25-amba-Obl', 'BRONCE', false),
  ('dto-indie-18-25-amba-Obl', 'PLATA', false),
  ('dto-indie-18-25-amba-Obl', 'ORO', false),
  ('dto-indie-18-25-amba-Obl', 'PLATINUM', false),
  ('dto-indie-26-35-amba-Obl', 'INDIE', true),
  ('dto-indie-26-35-amba-Obl', 'MEDIFEPLUS', false),
  ('dto-indie-26-35-amba-Obl', 'BRONCE_C', false),
  ('dto-indie-26-35-amba-Obl', 'BRONCE', false),
  ('dto-indie-26-35-amba-Obl', 'PLATA', false),
  ('dto-indie-26-35-amba-Obl', 'ORO', false),
  ('dto-indie-26-35-amba-Obl', 'PLATINUM', false),
  ('dto-indie-36-40-amba-Obl', 'INDIE', true),
  ('dto-indie-36-40-amba-Obl', 'MEDIFEPLUS', false),
  ('dto-indie-36-40-amba-Obl', 'BRONCE_C', false),
  ('dto-indie-36-40-amba-Obl', 'BRONCE', false),
  ('dto-indie-36-40-amba-Obl', 'PLATA', false),
  ('dto-indie-36-40-amba-Obl', 'ORO', false),
  ('dto-indie-36-40-amba-Obl', 'PLATINUM', false);

insert into discount_policy_schedule (discount_policy_id, seq, valor_pct, months) values
  ('opcion-1-nac-Vol', 1, -0.3, 3),
  ('opcion-1-nac-Vol', 2, -0.2, 2),
  ('opcion-1-nac-Vol', 3, -0.1, 2),
  ('opcion-2-nac-Vol', 1, -0.3, 3),
  ('opcion-2-nac-Vol', 2, -0.1, 6),
  ('opcion-1-nac-Obl', 1, -0.45, 2),
  ('opcion-1-nac-Obl', 2, -0.3, 3),
  ('opcion-1-nac-Obl', 3, -0.15, 2),
  ('opcion-2-nac-Obl', 1, -0.3, 6),
  ('opcion-2-nac-Obl', 2, -0.1, 3);
