-- RF-60/RF-61/RF-62: exclusión mutua Opción 1/2/3 (frontend, sin cambio de datos),
-- Opción 6 (nueva), y carga completa de Descuentos Tácticos regionales según
-- el documento de reglas de negocio vigente (reglas.docx). Corrige además 3
-- políticas tácticas que tenían un valor único sin distinguir por filial.

-- Opción 6
insert into discount_policies (id, nombre, tipo, region, categoria_scope, procedencia_gate, zona_filial, valor_pct, permanente, plazo_meses, concatenable, detalle) values
  ('opcion-6-nac-Vol', 'Opción 6', 'dto', 'Nac', 'Vol', '', null, -0.15, false, 12, true, '15% × 12 · Concatenable con Opción 4 · Titular y Cónyuge hasta 60 años'),
  ('opcion-6-nac-Obl', 'Opción 6', 'dto', 'Nac', 'Obl', '', null, -0.2, false, 12, true, '20% × 12 · Concatenable con Opción 4 · Titular y Cónyuge hasta 60 años');

insert into discount_policy_plan_rules (discount_policy_id, plan_code, aplica) values
  ('opcion-6-nac-Vol', 'INDIE', false),
  ('opcion-6-nac-Vol', 'MEDIFEPLUS', true),
  ('opcion-6-nac-Vol', 'BRONCE_C', true),
  ('opcion-6-nac-Vol', 'BRONCE', true),
  ('opcion-6-nac-Vol', 'PLATA', true),
  ('opcion-6-nac-Vol', 'ORO', true),
  ('opcion-6-nac-Vol', 'PLATINUM', true),
  ('opcion-6-nac-Obl', 'INDIE', false),
  ('opcion-6-nac-Obl', 'MEDIFEPLUS', true),
  ('opcion-6-nac-Obl', 'BRONCE_C', true),
  ('opcion-6-nac-Obl', 'BRONCE', true),
  ('opcion-6-nac-Obl', 'PLATA', true),
  ('opcion-6-nac-Obl', 'ORO', true),
  ('opcion-6-nac-Obl', 'PLATINUM', true);

-- Descuentos Tácticos nuevos (RF-62)
insert into discount_policies (id, nombre, tipo, region, categoria_scope, procedencia_gate, zona_filial, valor_pct, permanente, plazo_meses, concatenable, detalle) values
  ('dto-mes-36-40-bronce-gbasur-Obl', 'Dto Mes Bronce 36/40', 'dto', 'AMBA', 'Obl', '', 'GBA Sur', -0.05, false, 6, false, 'BRONCE 36 a 40 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-plata-amba-Obl', 'Dto Mes Plata 36/65', 'dto', 'AMBA', 'Obl', '', null, -0.1, false, 6, false, 'PLATA 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-oro-caba-Obl', 'Dto Mes Oro 36/65', 'dto', 'AMBA', 'Obl', '', 'CABA', -0.2, false, 6, false, 'ORO 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-plata-caba-Vol', 'Dto Mes Plata 36/65', 'dto', 'AMBA', 'Vol', '', 'CABA', -0.15, false, 6, false, 'PLATA 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-plata-gbasur-Vol', 'Dto Mes Plata 36/65', 'dto', 'AMBA', 'Vol', '', 'GBA Sur', -0.2, false, 6, false, 'PLATA 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-oro-gbasur-Vol', 'Dto Mes Oro 36/65', 'dto', 'AMBA', 'Vol', '', 'GBA Sur', -0.2, false, 6, false, 'ORO 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'Dto Mes 36/65', 'dto', 'Norte', 'Vol', '', 'Corrientes,Misiones', -0.2, false, 6, false, 'BRONCE, PLATA, ORO, PLATINUM 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-cordoba-Vol', 'Dto Mes 36/65', 'dto', 'Norte', 'Vol', '', 'Córdoba', -0.1, false, 6, false, 'BRONCE, PLATA, ORO, PLATINUM 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-60-noa-rosario-Vol', 'Dto Mes 36/60', 'dto', 'Norte', 'Vol', '', 'NOA,Rosario', -0.15, false, 6, false, 'BRONCE, PLATA, ORO, PLATINUM 36 a 60 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-60-bronce-sur-Obl', 'Dto Mes Bronce 18/60', 'dto', 'Sur', 'Obl', '', null, -0.05, false, 6, false, 'BRONCE 18 a 60 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'Dto Mes Oro 18/65', 'dto', 'Sur', 'Obl', '', 'San Juan', -0.3, false, 6, false, 'ORO 18 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-plata-sur-Vol', 'Dto Mes Plata 36/65', 'dto', 'Sur', 'Vol', '', null, -0.1, false, 6, false, 'PLATA 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'Dto Mes Oro 36/65', 'dto', 'Sur', 'Vol', '', 'Mendoza,Mercedes', -0.15, false, 6, false, 'ORO 36 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-65-oro-patagonia-Obl', 'Dto Mes Oro 18/65', 'dto', 'Patagonia', 'Obl', '', null, -0.15, false, 6, false, 'ORO 18 a 65 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-60-comahue-Vol', 'Dto Mes 36/60', 'dto', 'Patagonia', 'Vol', '', 'Comahue', -0.15, false, 6, false, 'BRONCE, PLATA, ORO, PLATINUM 36 a 60 años · Acumulable con Dto Estratégico'),
  ('dto-mes-36-60-patagonia-norte-Vol', 'Dto Mes 36/60', 'dto', 'Patagonia', 'Vol', '', 'Patagonia Norte', -0.1, false, 6, false, 'BRONCE, PLATA, ORO, PLATINUM 36 a 60 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'Dto Mes Oro 18/40', 'dto', 'Bahía/MDQ', 'Obl', '', null, -0.3, false, 6, false, 'ORO 18 a 40 años · Acumulable con Dto Estratégico'),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'Dto Mes Plata 18/65', 'dto', 'Bahía/MDQ', 'Vol', '', null, -0.1, false, 6, false, 'PLATA 18 a 65 años · Acumulable con Dto Estratégico');

insert into discount_policy_plan_rules (discount_policy_id, plan_code, aplica) values
  ('dto-mes-36-40-bronce-gbasur-Obl', 'INDIE', false),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'BRONCE_C', false),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'BRONCE', true),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'PLATA', false),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'ORO', false),
  ('dto-mes-36-40-bronce-gbasur-Obl', 'PLATINUM', false),
  ('dto-mes-36-65-plata-amba-Obl', 'INDIE', false),
  ('dto-mes-36-65-plata-amba-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-plata-amba-Obl', 'BRONCE_C', false),
  ('dto-mes-36-65-plata-amba-Obl', 'BRONCE', false),
  ('dto-mes-36-65-plata-amba-Obl', 'PLATA', true),
  ('dto-mes-36-65-plata-amba-Obl', 'ORO', false),
  ('dto-mes-36-65-plata-amba-Obl', 'PLATINUM', false),
  ('dto-mes-36-65-oro-caba-Obl', 'INDIE', false),
  ('dto-mes-36-65-oro-caba-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-oro-caba-Obl', 'BRONCE_C', false),
  ('dto-mes-36-65-oro-caba-Obl', 'BRONCE', false),
  ('dto-mes-36-65-oro-caba-Obl', 'PLATA', false),
  ('dto-mes-36-65-oro-caba-Obl', 'ORO', true),
  ('dto-mes-36-65-oro-caba-Obl', 'PLATINUM', false),
  ('dto-mes-36-65-plata-caba-Vol', 'INDIE', false),
  ('dto-mes-36-65-plata-caba-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-plata-caba-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-plata-caba-Vol', 'BRONCE', false),
  ('dto-mes-36-65-plata-caba-Vol', 'PLATA', true),
  ('dto-mes-36-65-plata-caba-Vol', 'ORO', false),
  ('dto-mes-36-65-plata-caba-Vol', 'PLATINUM', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'INDIE', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'BRONCE', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'PLATA', true),
  ('dto-mes-36-65-plata-gbasur-Vol', 'ORO', false),
  ('dto-mes-36-65-plata-gbasur-Vol', 'PLATINUM', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'INDIE', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'BRONCE', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'PLATA', false),
  ('dto-mes-36-65-oro-gbasur-Vol', 'ORO', true),
  ('dto-mes-36-65-oro-gbasur-Vol', 'PLATINUM', false),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'INDIE', false),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'BRONCE', true),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'PLATA', true),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'ORO', true),
  ('dto-mes-36-65-corrientes-misiones-Vol', 'PLATINUM', true),
  ('dto-mes-36-65-cordoba-Vol', 'INDIE', false),
  ('dto-mes-36-65-cordoba-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-cordoba-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-cordoba-Vol', 'BRONCE', true),
  ('dto-mes-36-65-cordoba-Vol', 'PLATA', true),
  ('dto-mes-36-65-cordoba-Vol', 'ORO', true),
  ('dto-mes-36-65-cordoba-Vol', 'PLATINUM', true),
  ('dto-mes-36-60-noa-rosario-Vol', 'INDIE', false),
  ('dto-mes-36-60-noa-rosario-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-60-noa-rosario-Vol', 'BRONCE_C', false),
  ('dto-mes-36-60-noa-rosario-Vol', 'BRONCE', true),
  ('dto-mes-36-60-noa-rosario-Vol', 'PLATA', true),
  ('dto-mes-36-60-noa-rosario-Vol', 'ORO', true),
  ('dto-mes-36-60-noa-rosario-Vol', 'PLATINUM', true),
  ('dto-mes-18-60-bronce-sur-Obl', 'INDIE', false),
  ('dto-mes-18-60-bronce-sur-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-60-bronce-sur-Obl', 'BRONCE_C', false),
  ('dto-mes-18-60-bronce-sur-Obl', 'BRONCE', true),
  ('dto-mes-18-60-bronce-sur-Obl', 'PLATA', false),
  ('dto-mes-18-60-bronce-sur-Obl', 'ORO', false),
  ('dto-mes-18-60-bronce-sur-Obl', 'PLATINUM', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'INDIE', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'BRONCE_C', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'BRONCE', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'PLATA', false),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'ORO', true),
  ('dto-mes-18-65-oro-sanjuan-Obl', 'PLATINUM', false),
  ('dto-mes-36-65-plata-sur-Vol', 'INDIE', false),
  ('dto-mes-36-65-plata-sur-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-plata-sur-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-plata-sur-Vol', 'BRONCE', false),
  ('dto-mes-36-65-plata-sur-Vol', 'PLATA', true),
  ('dto-mes-36-65-plata-sur-Vol', 'ORO', false),
  ('dto-mes-36-65-plata-sur-Vol', 'PLATINUM', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'INDIE', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'BRONCE_C', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'BRONCE', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'PLATA', false),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'ORO', true),
  ('dto-mes-36-65-oro-mendoza-mercedes-Vol', 'PLATINUM', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'INDIE', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'BRONCE_C', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'BRONCE', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'PLATA', false),
  ('dto-mes-18-65-oro-patagonia-Obl', 'ORO', true),
  ('dto-mes-18-65-oro-patagonia-Obl', 'PLATINUM', false),
  ('dto-mes-36-60-comahue-Vol', 'INDIE', false),
  ('dto-mes-36-60-comahue-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-60-comahue-Vol', 'BRONCE_C', false),
  ('dto-mes-36-60-comahue-Vol', 'BRONCE', true),
  ('dto-mes-36-60-comahue-Vol', 'PLATA', true),
  ('dto-mes-36-60-comahue-Vol', 'ORO', true),
  ('dto-mes-36-60-comahue-Vol', 'PLATINUM', true),
  ('dto-mes-36-60-patagonia-norte-Vol', 'INDIE', false),
  ('dto-mes-36-60-patagonia-norte-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-36-60-patagonia-norte-Vol', 'BRONCE_C', false),
  ('dto-mes-36-60-patagonia-norte-Vol', 'BRONCE', true),
  ('dto-mes-36-60-patagonia-norte-Vol', 'PLATA', true),
  ('dto-mes-36-60-patagonia-norte-Vol', 'ORO', true),
  ('dto-mes-36-60-patagonia-norte-Vol', 'PLATINUM', true),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'INDIE', false),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'MEDIFEPLUS', false),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'BRONCE_C', false),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'BRONCE', false),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'PLATA', false),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'ORO', true),
  ('dto-mes-18-40-oro-bahiamdq-Obl', 'PLATINUM', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'INDIE', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'MEDIFEPLUS', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'BRONCE_C', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'BRONCE', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'PLATA', true),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'ORO', false),
  ('dto-mes-18-65-plata-bahiamdq-Vol', 'PLATINUM', false);

-- Corrección de 3 políticas tácticas existentes (antes: un solo valor sin distinguir filial)
update discount_policies set zona_filial = 'GBA Sur', valor_pct = -0.2, detalle = 'ORO 18 a 65 años · GBA Sur · Acumulable con Dto Estratégico' where id = 'dto-mes-18-65-amba-oro-Obl';
update discount_policies set zona_filial = 'CABA', valor_pct = -0.15, detalle = 'ORO 36 a 65 años · CABA · Acumulable con Dto Estratégico' where id = 'dto-mes-36-65-amba-oro-Vol';
update discount_policies set zona_filial = 'Mendoza,Mercedes', valor_pct = -0.2, detalle = 'ORO 18 a 65 años · Mendoza/Mercedes · Acumulable con Dto Estratégico' where id = 'dto-mes-18-65-sur-oro-Obl';
